#! /bin/bash
host=10.1.1.60
name='root'
password='ta0mee'

#if [ $# -lt 1 ] ; then
    #echo "alterdb <db script file>";
    #exit;
#fi;


echo "db host:$host, name:$name, password:$password";
for((i=0;i<100;i++)); do
    doStr="drop database db_map_$i"
    mysql -u$name -p$password -Dtest -e "$doStr"
    echo;
done
